# Generated by Django 4.1.13 on 2024-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.CharField(default='Product Description', max_length=5000),
        ),
    ]
